### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by CombiAssu** [mxfolken/ps2_sdk_for_dummies#1]
First off, thank you for creating this.. It's funny my toolchain just broke and I'm in the middle of compiling. Once I use mount.exe I'm not sure what to do. Thank you!

**Comment by CombiAssu** [comment]
I'm an idiot, the instructions are right on the .bat.. It's been a long day, thanks!

**Comment by mxfolken** [comment]
Hello, thank you I hope you enjoy it, in the examples folder there are several sample exercises. You can also look for my book, to learn how to use the full SDK:

https://issuu.com/rolandofernandez9/docs/demo_book_programacion_ps2

Best regards!
